name: Cypress Tests

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Test
        run: yarn test

  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Cypress run
        uses: cypress-io/github-action@v4.x.x # use the explicit version number
        with:
          project: ./apps/sandbox
          build: npm run build
          start: npm start
