name: Unit Tests

on:
  push:
    branches:
      - main
      - 2.x
  pull_request:
    branches:
      - main
      - 2.x

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Test
        run: yarn test
